### ISSUE TITLE
Direct training of SNN missing

### ISSUE THREAD

**Issue by journey1234-liu** [SNNresearch/Spiking-UNet#2]
Thank you for your excellent work! However, snn_train.py is missing in the current repository. We could not find the function for directly training SNN from scratch. I'd be very grateful if you could provide us with some advice.

**Comment by hbfast** [comment]
Thank you for visiting our work! Our work is under review. I will release all the code and data to make you follow easily.  The code of direct training is easy. You define your network with spiking neurons to replace the relu activation in our network.

**Comment by hbfast** [comment]
Thank you for visiting our work! Our work is under review. I will release all the code and data to make you follow easily when the paper is accepted. The code of direct training is easy. You define your network with spiking neurons to replace the ReLU activation in our network.

**Comment by HebeiFast** [comment]
Thank you for visiting our work! Our work is under review. I will release all the code and data to make you follow easily after the paper is accepted. The code of direct training is easy. You define your network with spiking neurons to replace the ReLU activation in our network.
