### ISSUE TITLE
CSBD Dataset in HDF5 Format

### ISSUE THREAD

**Issue by Rah-xephon** [SNNresearch/Spiking-UNet#3]
Thanks for this great work! I am a beginner of SNN and image segmentation, I could only find CSBD/SBD dataset in matlab format or "seg" fomat. Could you tell me how to get CSBD/SBD in HDF5 format? 
Good luck to you！

**Comment by HebeiFast** [comment]
I convert the dataset into hdf5 format for our cloud platform. The training data is from www2.eecs.berkeley.edu/Research/Projects/CS/vision/bsds. The test data is from https://www.kaggle.com/code/mpwolke/berkeley-segmentation-dataset-68/input for BSD and https://github.com/clausmichele/CBSD68-dataset/tree/master for CBSD.
